config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'
  resources :tweets do
    collection do
      get  :ten_latest
      post :tweet
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  def self.ten_latest
    Rails.cache.read(:ten_latest_tweets)
  end

  def self.ten_latest!(save = true)
    Rails.cache.write :ten_latest_tweets, ten_latest_hash
    # WIP save to DB
    # save_ten_latest(ten_latest) if save
    ten_latest
  end

  def self.save_ten_latest(ten_latest_hash)
    ten_latest_hash.each do |topic, oembeds|
      oembeds.each do |oembed|
        create html: oembed.html, topic: topic
      end
    end
  end

  def self.ten_latest_from_db
    order('created_at desc').where(topic: topics[0]).limit(10)
    .union( order('created_at desc').where(topic: topics[1]).limit(10) )
    .union( order('created_at desc').where(topic: topics[2]).limit(10) )
  end

  def self.ten_latest_from_db!
    Rails.cache.write :ten_latest_tweets, ten_latest_from_db
    ten_latest_from_db
  end

  # Output:
  # {
  #   'healthcare'  => [oembed1, ...],
  #   'nasa'        => [oembed2, ...],
  #   'open source' => [oembed3, ...],
  # }
  def self.ten_latest_hash
    Hash[ten_latest_array]
  end

  # Output:
  # [
  #   ['healthcare', [oembed1, ...]],
  #   ['nasa', [oembed2, ...]],
  #   ['open source', [oembed3, ...]],
  # ]
  def self.ten_latest_array
    topics.map do |topic|
      ids = ten_latest_ids topic

      oembeds = twitter.oembeds ids, omit_script: true

      [topic, oembeds]
    end
  end

  # Output: [1,2,3,4]
  def self.ten_latest_ids(query)
    twitter.search(query, result_type: "recent").take(10).map &:id
  end

  def self.topics
    ['healthcare', 'nasa', 'open source']
  end

  # Debug method
  def self.api_limits
    twitter.get 'https://api.twitter.com/1.1/application' +
      '/rate_limit_status.json?resources=help,users,search,statuses,oembed'
  end

  # Debug method
  def self.search_api_limits
    api_limits[:resources][:search]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < InheritedResources::Base
  respond_to :json

  def ten_latest
    render json: Tweet.ten_latest
  end

  def tweet
    render json: twitter.update(params[:message])
  end

  private

    # redirect to collection_url instead
    def resource_url; nil end

    def tweet_params
      params.require(:tweet).permit(:html)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @tweets = Tweet.ten_latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html(ng-app='app')
  head
    title TenLatestTweets
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  body
    = yield

app/views/tweets/_form.html.slim
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      ul
        - @tweet.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :html
    = f.text_field :html
  .actions = f.submit

app/views/tweets/edit.html.slim
h1 Editing tweet

== render 'form'

= link_to 'Show', @tweet
'|
= link_to 'Back', tweets_path

app/views/tweets/index.html.slim
h1 Listing tweets

table
  thead
    tr
      th Html
      th
      th
      th

  tbody
    - @tweets.each do |tweet|
      tr
        td = tweet.html
        td = link_to 'Show', tweet
        td = link_to 'Edit', edit_tweet_path(tweet)
        td = link_to 'Destroy', tweet, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.slim
h1 New tweet

== render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.slim
p#notice = notice

p
  strong Html:
  = @tweet.html

= link_to 'Edit', edit_tweet_path(@tweet)
'|
= link_to 'Back', tweets_path

app/views/welcome/index.html.slim
.navbar-fixed
  nav.black
    .nav-wrapper
      | &emsp;
      a.brand-logo href='#' 10 Latest Tweets
      / a.brand-logo.center href='javascript:void(0)' onclick='toggleSync()' title='Toggle Sync'
        i.material-icons.rotate loop
      ul#nav-mobile.right.hide-on-med-and-down
        li
          a href="#healthcare" Healthcare
        li
          a href="#nasa" NASA
        li
          a href="#open-source" Open Source
        li.tweet-button
          a(class="twitter-share-button"
          href="https://twitter.com/intent/tweet"
          data-text="Check this awesome site"
          data-size="large")
            | Tweet
          / a.grey.waves-effect.waves-light.btn.modal-trigger href="#new-tweet"
            i.tiny.material-icons mode_edit


/! Modal Structure
#new-tweet.modal ng-controller='TweetCtrl'
  .modal-content
    h4 Share what you are thinking
    form ng-submit='tweet()'
      input name='message' ng-model='formData.message'

  .modal-footer
    a.modal-action.modal-close.waves-effect.waves-green.btn-flat ng-click='tweet()'
     | Post now


#preloader
  .preloader-wrapper.big.active
    .spinner-layer.spinner-blue-only
      .circle-clipper.left
        .circle
      .gap-patch
        .circle
      .circle-clipper.right
        .circle


.grids ng-controller='GridsCtrl'

  / Client side with Angular
  .card(id='{{category | dasherize}}' ng-repeat='(category, oembeds) in data'
    repeat-done='renderTwitter()')
    .card-content
      h1.tl-title
        | {{category | titleize}} Stories
      .grid
        span ng-repeat='oembed in oembeds' ng-bind-html='oembed.html | unescape'


  / Client side with Ractive
  #ractive
  script id='ractive-template' type='text/ractive'
    | {{#tweetsByCategory:category}}
    .card id="{{S(category).dasherize().s}}"
      .card-content
        h1.tl-title
          | {{S(category).titleCase().s}} Stories
        .grid
          | {{#.}}
          | {{{html}}}
          | {{/}}

    | {{/}}

  / Server side
  /- Tweet.ten_latest.each do |topic, oembeds|

    .card id=topic.parameterize
      .card-content
        h1.tl-title
          = "#{topic.titleize} Stories"
        .grid
          - oembeds.each do |oembed|
            == oembed.html